FROM oven/bun:latest as builder

WORKDIR /app/dashboard

COPY package.json bun.lockb* ./
RUN bun install

COPY . .
RUN bun run build

# Production image
FROM nginx:alpine

COPY --from=builder /app/dashboard/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
